### PR TITLE
Correct include dir in Makefile

### PR DESCRIPTION
**Pull request by adtrevor**
In `api.h`, we have:
```c
#include <mycore/myosi.h>
#include <mycore/incoming.h>
#include <mycore/mystring.h>
#include <mycore/utils/mchar_asy
```

So path is relative to `/include`, not `/incude/mycore` etc...

I encountered a bug with the old pc config and this new one fixes the issue.

### CODE REVIEW

**Comment by adtrevor** [comment]
@lexborisov Do you think that makes sense?

**Comment by lexborisov** [comment]
@adtrevor 
I will definitely watch the patch tomorrow. 
Thank you for the report!

**Comment by lexborisov** [comment]
@adtrevor 
Thanks for the PR! Merged.

**Comment by adtrevor** [comment]
@lexborisov Happy to contribute! 😃

**Pull request merged**
