### PR TITLE
chore(packages): add automatic package build

### LINKED ISSUE #99: Готовые пакеты
@lexborisov Во-первых, спасибо за проделанный титанический труд :+1: 

Есть одна проблема, библиотеку хотелось бы иметь в пакетах для различных дистрибутивов, так как тянуть инструменты сборки на production не хочется.

Всем понятно, что вручную этого делать никто не будет :smile: Я использую [packpack](https://github.com/packpack/packpack), заданным требованиям он отвечает.

Если к этому есть интерес, я бы мог открыть PR реализующий это.

### PR DESCRIPTION
**Pull request by layershifter**
# WIP

Fixes #99.

### TODO

- [ ] finish RHEL spec
- [ ] update CI config
- [ ] add instructions

### CODE REVIEW

**Comment by lexborisov** [comment]
This is awesome!
Thanks!

**Comment by layershifter** [comment]
@lexborisov Stop-stop :cry: It's works in progress.

**Comment by layershifter** [comment]
This PR wasn't ready to merge, I don't finished all things that it requires.

**Comment by lexborisov** [comment]
:)
@layershifter It's okay, I looked, there's nothing breaking
But of course I hurried
But, it's okay

**Pull request merged**
