### PR TITLE
improved docx

### PR DESCRIPTION
**Pull request by Tanu-creater**

### CODE REVIEW

**Comment by lexborisov** [comment]
@Tanu-creater 

Thanks!

**Comment by Tanu-creater** [comment]
That's all right.

**Comment by CoolOppo** [comment]
Actually, the grammar is very wrong now after this change.

**Comment by tanukataria** [comment]
Ya,i think you're right.

**Comment by lexborisov** [comment]
@CoolOppo 

Thanks, fixed in [7ad40c6](https://github.com/lexborisov/myhtml/commit/7ad40c6343f8f7721af2586e7c27685773d83d1f).

**Pull request merged**
