### PR TITLE
Changed Debian packaging

### PR DESCRIPTION
**Pull request by mody**
- removed unused dependency on cdbs
- simplified debian/rules

### CODE REVIEW

**Comment by lexborisov** [comment]
Thanks!

**Comment by mody** [comment]
I'm now investigating why your `mycss` won't compile with Debianized `myhtml`. Seems like it can't work.

**Comment by lexborisov** [comment]
@mody mycss long abandoned. The last working version is in [Modest](https://github.com/lexborisov/Modest) project.

**Comment by mody** [comment]
Aha, ok. Thanks.

**Pull request merged**
