### PR TITLE
chore(packages): add automatic package build

### PR DESCRIPTION
**Pull request by layershifter**
### What it does?

This PR and the previous #108 add automatic package build feature to this repository using [packpack](https://github.com/packpack/packpack). It will build packages with binaries and headers for popular distros: Debian, Ubuntu, CentOS and Fedora, see `matrix` in Travis config. Built packages will be automatically uploaded to the [Packagecloud](https://packagecloud.io/), it will make the library more accesible to end-users.

### How to trigger build?

Package build will be scheduled only when you push a tag to `master` branch (see `scripts` in Travis config). So, if you want to make a new release of packages, you can simply go to the [releases ](https://github.com/lexborisov/myhtml/releases) tab and ship it :smile: 

**Keep in mind:** you need to follow the [semver](http://semver.org/) pattern there (_x.y.z_), release tag should begin from a _v_ char (_v4.0.1_).

### Configuring

* register a free [Packagecloud](https://packagecloud.io/) account and create a repository
* add the following environment variables to the project settings on [Travis CI](https://github.com/packpack/packpack/blob/master/doc/travisenv.png):
  * PACKAGECLOUD_TOKEN=<token> (secret)
  * PACKAGECLOUD_USER=<username> (public)
  * PACKAGECLOUD_REPO=<reponame> (public)
* make a new release tagged with `v4.0.1`.
* PROFIT :smile:

### CODE REVIEW

**Comment by layershifter** [comment]
@lexborisov Please, don't merge this. I want to test this in my fork before we start.

**Comment by layershifter** [comment]
Here is update, it's almost [works](https://travis-ci.org/layershifter/myhtml/builds/242484327). There is something wrong with CentOS 6/7, you can check packages [there](https://packagecloud.io/layershifter/myhtml).

I want to fix CentOS' builds and check that RPM packages work as expected tomorrow :sleeping:

**Comment by lexborisov** [comment]
Great job! Thanks!

**Comment by layershifter** [comment]
Tested on Fedora 25:

> $ curl -s https://packagecloud.io/install/repositories/layershifter/myhtml/script.rpm.sh | sudo bash
> $ yum install libmyhtml-devel -y
> $ gcc example.c -lmyhtml -o example
> $ ./example 
> Original tree:
> <html><div></div></html>For a test; Create and delete 100000 attrs...
> Modified tree:
> <html><div key="value"></div></html>Get attr by key name "key": value

Works like a charm :+1: 

----------

However, there is still something wrong with my CentOS repo on PackageCloud. I asked them on their Slack and email. It's a single thing that stops us from the merge.

**Comment by lexborisov** [comment]
Impressive. You really help with the project.
Let's hope that the issue with CentOS will be solved.

**Comment by layershifter** [comment]
Yes, it was a bug, now everything works perfectly:

- [branch build](https://travis-ci.org/layershifter/myhtml/builds/242742406) (build skipped)
- [master build](https://travis-ci.org/layershifter/myhtml/builds/243161074) (build skipped)
- [tag build](https://travis-ci.org/layershifter/myhtml/builds/243156788) (build performed)

**Comment by layershifter** [comment]
@lexborisov We're ready to go. Don't forget to register and setup an PackageCloud's account before release.

**Comment by lexborisov** [comment]
Ok, today, closer to the evening, I'll deal with this.
Thanks for the help with automatic package build!

**Comment by lexborisov** [comment]
@layershifter why PackageCloud? Can we do without them? In other words, are they mandatory for the formation of packages?

**Comment by layershifter** [comment]
@lexborisov PackageCloud is not needed to generate packages, however they provide a hosted repository  which allows users to receive updates of package after its release. There is also an [ability](https://docs.travis-ci.com/user/deployment/releases/) to upload packages to the Github Releales, but I don't checked it. However, I think that it's an important thing for the modern software, take a look on the Tarantool's [download page](https://tarantool.org/download.html).

Here is a live example: I want to build binding for PHP and then also upload packages to the PackageCloud. It will require the MyHTML library as you understand. And this is how the installation instruction will look like:
```sh
curl -s https://packagecloud.io/install/repositories/lexborisov/myhtml/script.deb.sh | sudo bash
curl -s https://packagecloud.io/install/repositories/layershifter/php-myhtml/script.deb.sh | sudo bash
apt-get install php-myhtml
```
And update:
```sh
apt-get install --only-upgrade libmyhtml php-myhtml
```

It's much better then follow to repository on Github and search for the latest version. Also, it's simplifies the automation build like a Docker container.

**Comment by lexborisov** [comment]
In fact, I can do the same thing on my own server, right?
And users will simply specify my repository for ```yum``` or some else like a Tarantool.

Simply, literally today there were talks about buying a server for this project (modest, myhtml)

P.S.: You have a php binding for myhtml? Share?

**Comment by layershifter** [comment]
Yes, but it will not so easy as I remember :smile: It will be easier to [setup mirroring](https://packagecloud.io/layershifter/myhtml/mirror) from PackageCloud's repo to own server.

No, but I want to build it, possible I will have enough time for it in near future. I've made a binding for [gumbo](https://github.com/layershifter/gumbo-php) previously, but at now I want a more advanced solution that can be shipped to our infrastructure without problems and build automation is one most important things.

**Comment by lexborisov** [comment]
Done
https://packagecloud.io/Modest/myhtml

**Pull request merged**
